version: "3"
services:
  core-api:
    build: .
    tty: true
    ports:
      - "8081:8080"
    volumes:
      - "./core-api:/go/src/app"

  device-api:
    build: .
    tty: true
    ports:
      - "8082:8080"
    volumes:
      - "./device-api:/go/src/app"
      
  psql:
    container_name: "psqldb"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dbuser
      POSTGRES_DB: database
    ports:
      - "5432:5432"

