// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MeasurementHistoryServiceClient is the client API for MeasurementHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeasurementHistoryServiceClient interface {
	RecordHistory(ctx context.Context, in *RecordHistoryRequest, opts ...grpc.CallOption) (*MeasurementHistory, error)
}

type measurementHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeasurementHistoryServiceClient(cc grpc.ClientConnInterface) MeasurementHistoryServiceClient {
	return &measurementHistoryServiceClient{cc}
}

func (c *measurementHistoryServiceClient) RecordHistory(ctx context.Context, in *RecordHistoryRequest, opts ...grpc.CallOption) (*MeasurementHistory, error) {
	out := new(MeasurementHistory)
	err := c.cc.Invoke(ctx, "/MeasurementHistoryService/RecordHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeasurementHistoryServiceServer is the server API for MeasurementHistoryService service.
// All implementations must embed UnimplementedMeasurementHistoryServiceServer
// for forward compatibility
type MeasurementHistoryServiceServer interface {
	RecordHistory(context.Context, *RecordHistoryRequest) (*MeasurementHistory, error)
	mustEmbedUnimplementedMeasurementHistoryServiceServer()
}

// UnimplementedMeasurementHistoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMeasurementHistoryServiceServer struct {
}

func (UnimplementedMeasurementHistoryServiceServer) RecordHistory(context.Context, *RecordHistoryRequest) (*MeasurementHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordHistory not implemented")
}
func (UnimplementedMeasurementHistoryServiceServer) mustEmbedUnimplementedMeasurementHistoryServiceServer() {
}

// UnsafeMeasurementHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeasurementHistoryServiceServer will
// result in compilation errors.
type UnsafeMeasurementHistoryServiceServer interface {
	mustEmbedUnimplementedMeasurementHistoryServiceServer()
}

func RegisterMeasurementHistoryServiceServer(s grpc.ServiceRegistrar, srv MeasurementHistoryServiceServer) {
	s.RegisterService(&MeasurementHistoryService_ServiceDesc, srv)
}

func _MeasurementHistoryService_RecordHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasurementHistoryServiceServer).RecordHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MeasurementHistoryService/RecordHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasurementHistoryServiceServer).RecordHistory(ctx, req.(*RecordHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeasurementHistoryService_ServiceDesc is the grpc.ServiceDesc for MeasurementHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeasurementHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MeasurementHistoryService",
	HandlerType: (*MeasurementHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordHistory",
			Handler:    _MeasurementHistoryService_RecordHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/measurement_history.proto",
}
